import { Paciente, HerramientaAprendizaje, Medida, Biomarcador, BiomarcadorTipo } from '@/types';

export const pacientesMock: Paciente[] = [
  {
    id: '1',
    nombre: 'María García López',
    dni: '12345678A',
    telefono: '612345678',
    fechaNacimiento: '1985-03-15',
    email: 'maria.garcia@email.com',
    direccion: 'Calle Mayor 123',
    codigoPostal: '28001',
    localidad: 'Madrid',
    gruposAlimentarios: ['frutas', 'legumbres', 'pescadoBlanco', 'lacteos'],
    ingestas: [
      { tipo: 'desayuno', realiza: true, horario: '08:00', descripcion: 'Tostadas con aceite y café' },
      { tipo: 'almuerzo', realiza: false, horario: '', descripcion: '' },
      { tipo: 'comida', realiza: true, horario: '14:00', descripcion: 'Variado' },
      { tipo: 'merienda', realiza: true, horario: '17:30', descripcion: 'Fruta o yogur' },
      { tipo: 'cena', realiza: true, horario: '21:00', descripcion: 'Ensalada o sopa' },
    ],
    recomendadoPor: 'Amiga del trabajo',
    aguaDiaria: '1.5 litros',
    otrosLiquidos: 'Café, infusiones',
    habitosAlimenticios: 'Regulares, intento comer sano',
    cansancioDia: 'Sí, después de comer',
    problemasDigestion: 'A veces hinchazón',
    pesoIdeal: '60 kg',
    deporte: { practica: true, cual: 'Yoga y caminar', frecuencia: '3 veces/semana' },
    calidadSueno: 'Regular, me despierto a veces',
    dietaAnterior: 'Hice dieta mediterránea hace 2 años',
    estadoSalud: 'Bueno en general',
    dolencias: [
      { tipo: 'estrenimiento', activa: true },
      { tipo: 'jaquecas', activa: true, notas: 'Ocasionales' },
    ],
    medicamentos: [],
    trabajo: { activo: true, tipo: 'Oficina', horario: '9:00-18:00' },
    estres: { nivel: 6, motivo: 'Trabajo', afectaSalud: 'Sí, como más cuando estoy estresada' },
    fechaRegistro: '2024-01-15',
    activo: true,
  },
  {
    id: '2',
    nombre: 'Carlos Martínez Ruiz',
    dni: '87654321B',
    telefono: '623456789',
    fechaNacimiento: '1990-07-22',
    email: 'carlos.martinez@email.com',
    direccion: 'Avenida Principal 45',
    codigoPostal: '08001',
    localidad: 'Barcelona',
    gruposAlimentarios: ['carneRoja', 'harinas', 'quesos', 'cafes'],
    ingestas: [
      { tipo: 'desayuno', realiza: true, horario: '07:30', descripcion: 'Cereales con leche' },
      { tipo: 'almuerzo', realiza: true, horario: '11:00', descripcion: 'Bocadillo' },
      { tipo: 'comida', realiza: true, horario: '14:30', descripcion: 'Menú del día' },
      { tipo: 'merienda', realiza: false, horario: '', descripcion: '' },
      { tipo: 'cena', realiza: true, horario: '21:30', descripcion: 'Pizza o pasta' },
    ],
    recomendadoPor: 'Médico de cabecera',
    aguaDiaria: '1 litro',
    otrosLiquidos: 'Refrescos, cerveza ocasional',
    habitosAlimenticios: 'Mejorable, como mucha comida rápida',
    cansancioDia: 'Sí, por las tardes',
    problemasDigestion: 'Acidez frecuente',
    pesoIdeal: '80 kg',
    deporte: { practica: false, cual: '', frecuencia: '' },
    calidadSueno: 'Malo, duermo pocas horas',
    dietaAnterior: 'No',
    estadoSalud: 'Regular',
    dolencias: [
      { tipo: 'colesterolAlto', activa: true },
      { tipo: 'gastritis', activa: true },
    ],
    medicamentos: [
      { id: '1', farmaco: 'Omeprazol', dosis: '20mg', motivo: 'Gastritis', tiempo: '6 meses' },
    ],
    trabajo: { activo: true, tipo: 'Comercial', horario: 'Variable' },
    estres: { nivel: 8, motivo: 'Objetivos de ventas', afectaSalud: 'Sí, mucho' },
    fechaRegistro: '2024-02-20',
    activo: true,
  },
  {
    id: '3',
    nombre: 'Ana Fernández Vega',
    dni: '11223344C',
    telefono: '634567890',
    fechaNacimiento: '1978-11-08',
    email: 'ana.fernandez@email.com',
    direccion: 'Plaza del Sol 7',
    codigoPostal: '41001',
    localidad: 'Sevilla',
    gruposAlimentarios: ['frutas', 'legumbres', 'pescadoAzul', 'semillas', 'tes'],
    ingestas: [
      { tipo: 'desayuno', realiza: true, horario: '08:30', descripcion: 'Fruta y tostada integral' },
      { tipo: 'almuerzo', realiza: true, horario: '11:30', descripcion: 'Frutos secos' },
      { tipo: 'comida', realiza: true, horario: '14:00', descripcion: 'Comida casera equilibrada' },
      { tipo: 'merienda', realiza: true, horario: '18:00', descripcion: 'Té con galletas integrales' },
      { tipo: 'cena', realiza: true, horario: '20:30', descripcion: 'Verduras y proteína' },
    ],
    recomendadoPor: 'Instagram',
    aguaDiaria: '2 litros',
    otrosLiquidos: 'Té verde, infusiones',
    habitosAlimenticios: 'Buenos, muy consciente',
    cansancioDia: 'No',
    problemasDigestion: 'No',
    pesoIdeal: '58 kg',
    deporte: { practica: true, cual: 'Pilates y natación', frecuencia: '4 veces/semana' },
    calidadSueno: 'Muy bueno',
    dietaAnterior: 'Vegetariana durante 2 años',
    estadoSalud: 'Muy bueno',
    dolencias: [],
    medicamentos: [],
    trabajo: { activo: true, tipo: 'Profesora', horario: '8:00-15:00' },
    estres: { nivel: 3, motivo: 'Normal del día a día', afectaSalud: 'No' },
    fechaRegistro: '2024-03-10',
    activo: true,
  },
];

export const herramientasMock: HerramientaAprendizaje[] = [
  {
    id: '1',
    titulo: 'Guía de alimentación saludable',
    descripcion: 'Documento completo sobre los principios de una alimentación equilibrada y saludable.',
    tipo: 'pdf',
    url: '/docs/guia-alimentacion.pdf',
    categoria: 'Nutrición básica',
    fechaCreacion: '2024-01-01',
  },
  {
    id: '2',
    titulo: 'Recetas bajas en calorías',
    descripcion: 'Colección de 50 recetas saludables con menos de 400 calorías por porción.',
    tipo: 'pdf',
    url: '/docs/recetas-bajas-calorias.pdf',
    categoria: 'Recetas',
    fechaCreacion: '2024-01-15',
  },
  {
    id: '3',
    titulo: 'Cómo leer etiquetas nutricionales',
    descripcion: 'Video explicativo sobre cómo interpretar la información nutricional de los productos.',
    tipo: 'video',
    url: 'https://youtube.com/example',
    categoria: 'Educación',
    fechaCreacion: '2024-02-01',
  },
  {
    id: '4',
    titulo: 'Infografía: Plato saludable',
    descripcion: 'Representación visual de las proporciones ideales en cada comida.',
    tipo: 'infografia',
    url: '/docs/plato-saludable.png',
    categoria: 'Nutrición básica',
    fechaCreacion: '2024-02-10',
  },
  {
    id: '5',
    titulo: 'Gestión del estrés y alimentación',
    descripcion: 'Artículo sobre la relación entre el estrés y los hábitos alimenticios.',
    tipo: 'articulo',
    url: '/docs/estres-alimentacion.pdf',
    categoria: 'Bienestar',
    fechaCreacion: '2024-03-01',
  },
];

// Medidas con la nueva estructura completa
export const medidasMock: Medida[] = [
  {
    id: '1',
    pacienteId: '1',
    fecha: '2024-01-15',
    hora: '10:30',
    bioimpedancia: {
      peso: 68,
      grasaSubcutanea: 28,
      huesos: 2.8,
      agua: 52,
      musculo: 42,
      metabolismoBasal: 1380,
      edadMetabolica: 42,
      grasaVisceral: 7,
      azucarSangre: 95,
      tension: '120/80',
      flexibilidad: 6,
      phSaliva: 7.0,
      imc: 25.0,
    },
    segmental: {
      brazoIzq: { kg: 2.1, porcentaje: 32 },
      brazoDer: { kg: 2.2, porcentaje: 33 },
      tronco: { kg: 8.5, porcentaje: 28 },
      piernaIzq: { kg: 5.8, porcentaje: 30 },
      piernaDer: { kg: 5.9, porcentaje: 31 },
    },
    plicometria: {
      bicipital: 8,
      tricipital: 18,
      subEscapular: 16,
      abdominal: 22,
      suprailiaco: 20,
      muslo: 24,
      gemelo: 12,
    },
    antropometria: {
      hombro: 98,
      biceps: 28,
      bicepsContraido: 30,
      pecho: 92,
      cintura: 78,
      ombligo: 82,
      cadera: 98,
      muneca: 15,
      gluteos: 100,
      cuadriceps: 54,
      gemelo: 36,
      tobillo: 22,
    },
  },
  {
    id: '2',
    pacienteId: '1',
    fecha: '2024-02-15',
    hora: '10:15',
    bioimpedancia: {
      peso: 66.5,
      grasaSubcutanea: 27,
      huesos: 2.8,
      agua: 53,
      musculo: 42.5,
      metabolismoBasal: 1390,
      edadMetabolica: 41,
      grasaVisceral: 6,
      azucarSangre: 92,
      tension: '118/78',
      flexibilidad: 7,
      phSaliva: 7.1,
      imc: 24.4,
    },
    segmental: {
      brazoIzq: { kg: 2.0, porcentaje: 31 },
      brazoDer: { kg: 2.1, porcentaje: 32 },
      tronco: { kg: 8.0, porcentaje: 27 },
      piernaIzq: { kg: 5.7, porcentaje: 29 },
      piernaDer: { kg: 5.8, porcentaje: 30 },
    },
    plicometria: {
      bicipital: 7,
      tricipital: 17,
      subEscapular: 15,
      abdominal: 20,
      suprailiaco: 18,
      muslo: 22,
      gemelo: 11,
    },
    antropometria: {
      hombro: 98,
      biceps: 28,
      bicepsContraido: 30,
      pecho: 91,
      cintura: 76,
      ombligo: 80,
      cadera: 96,
      muneca: 15,
      gluteos: 98,
      cuadriceps: 53,
      gemelo: 36,
      tobillo: 22,
    },
  },
  {
    id: '3',
    pacienteId: '1',
    fecha: '2024-03-15',
    hora: '10:00',
    bioimpedancia: {
      peso: 65,
      grasaSubcutanea: 26,
      huesos: 2.8,
      agua: 54,
      musculo: 43,
      metabolismoBasal: 1400,
      edadMetabolica: 40,
      grasaVisceral: 6,
      azucarSangre: 90,
      tension: '115/75',
      flexibilidad: 7,
      phSaliva: 7.2,
      imc: 23.9,
    },
    segmental: {
      brazoIzq: { kg: 1.9, porcentaje: 30 },
      brazoDer: { kg: 2.0, porcentaje: 31 },
      tronco: { kg: 7.5, porcentaje: 26 },
      piernaIzq: { kg: 5.5, porcentaje: 28 },
      piernaDer: { kg: 5.6, porcentaje: 29 },
    },
    plicometria: {
      bicipital: 6,
      tricipital: 16,
      subEscapular: 14,
      abdominal: 18,
      suprailiaco: 16,
      muslo: 20,
      gemelo: 10,
    },
    antropometria: {
      hombro: 97,
      biceps: 27,
      bicepsContraido: 30,
      pecho: 90,
      cintura: 74,
      ombligo: 78,
      cadera: 95,
      muneca: 15,
      gluteos: 97,
      cuadriceps: 52,
      gemelo: 35,
      tobillo: 22,
    },
  },
  {
    id: '4',
    pacienteId: '1',
    fecha: '2024-04-15',
    hora: '10:30',
    bioimpedancia: {
      peso: 64,
      grasaSubcutanea: 25,
      huesos: 2.9,
      agua: 55,
      musculo: 43.5,
      metabolismoBasal: 1410,
      edadMetabolica: 39,
      grasaVisceral: 5,
      azucarSangre: 88,
      tension: '112/72',
      flexibilidad: 8,
      phSaliva: 7.2,
      imc: 23.5,
    },
    segmental: {
      brazoIzq: { kg: 1.8, porcentaje: 29 },
      brazoDer: { kg: 1.9, porcentaje: 30 },
      tronco: { kg: 7.2, porcentaje: 25 },
      piernaIzq: { kg: 5.4, porcentaje: 27 },
      piernaDer: { kg: 5.5, porcentaje: 28 },
    },
    plicometria: {
      bicipital: 5,
      tricipital: 15,
      subEscapular: 13,
      abdominal: 16,
      suprailiaco: 14,
      muslo: 18,
      gemelo: 9,
    },
    antropometria: {
      hombro: 97,
      biceps: 27,
      bicepsContraido: 30,
      pecho: 89,
      cintura: 73,
      ombligo: 76,
      cadera: 94,
      muneca: 15,
      gluteos: 96,
      cuadriceps: 52,
      gemelo: 35,
      tobillo: 22,
    },
  },
];

// Biomarcadores con los 10 tipos específicos
export const biomarcadoresMock: Biomarcador[] = [
  // ========== PACIENTE 1 - Los 10 biomarcadores ==========
  {
    id: '1',
    pacienteId: '1',
    tipo: 'gastrointestinal',
    porcentaje: 65,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Aumentar fibra soluble gradualmente', completada: true },
      { id: '2', descripcion: 'Probióticos diarios', completada: false },
      { id: '3', descripcion: 'Masticar lentamente (20 veces)', completada: false },
    ],
  },
  {
    id: '2',
    pacienteId: '1',
    tipo: 'biorritmo',
    porcentaje: 70,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Cenar 3h antes de dormir', completada: true },
      { id: '2', descripcion: 'Exposición solar matutina 15 min', completada: true },
      { id: '3', descripcion: 'Evitar pantallas 1h antes de dormir', completada: false },
    ],
  },
  {
    id: '3',
    pacienteId: '1',
    tipo: 'osteoarticular',
    porcentaje: 80,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Calcio 1000mg/día', completada: true },
      { id: '2', descripcion: 'Vitamina D3 2000 UI', completada: true },
    ],
  },
  {
    id: '4',
    pacienteId: '1',
    tipo: 'datosCliniclos',
    porcentaje: 75,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Analítica completa trimestral', completada: true },
      { id: '2', descripcion: 'Control tensión semanal', completada: true },
      { id: '3', descripcion: 'Registro de síntomas', completada: false },
    ],
  },
  {
    id: '5',
    pacienteId: '1',
    tipo: 'estetica',
    porcentaje: 60,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Hidratación 2L agua/día', completada: true },
      { id: '2', descripcion: 'Colágeno hidrolizado', completada: false },
      { id: '3', descripcion: 'Antioxidantes en dieta', completada: true },
    ],
  },
  {
    id: '6',
    pacienteId: '1',
    tipo: 'psiconutricion',
    porcentaje: 55,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Diario de alimentación emocional', completada: false },
      { id: '2', descripcion: 'Técnicas de mindful eating', completada: false },
      { id: '3', descripcion: 'Identificar triggers de ansiedad', completada: true },
    ],
  },
  {
    id: '7',
    pacienteId: '1',
    tipo: 'rendimientoDeportivo',
    porcentaje: 72,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Proteína post-entreno 30min', completada: true },
      { id: '2', descripcion: 'Carbohidratos complejos pre-entreno', completada: true },
      { id: '3', descripcion: 'BCAA en días de alta intensidad', completada: false },
    ],
  },
  {
    id: '8',
    pacienteId: '1',
    tipo: 'hormonas',
    porcentaje: 68,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Reducir disruptores endocrinos', completada: false },
      { id: '2', descripcion: 'Zinc y magnesio antes de dormir', completada: true },
      { id: '3', descripcion: 'Grasas saludables en cada comida', completada: true },
    ],
  },
  {
    id: '9',
    pacienteId: '1',
    tipo: 'sistemaInmune',
    porcentaje: 78,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Vitamina C 1000mg/día', completada: true },
      { id: '2', descripcion: 'Equinácea en cambios de estación', completada: false },
      { id: '3', descripcion: 'Reducir azúcares simples', completada: true },
    ],
  },
  {
    id: '10',
    pacienteId: '1',
    tipo: 'microbiota',
    porcentaje: 60,
    fecha: '2024-04-15',
    tareas: [
      { id: '1', descripcion: 'Alimentos fermentados 3x/semana', completada: true },
      { id: '2', descripcion: 'Prebióticos (inulina, FOS)', completada: false },
      { id: '3', descripcion: 'Reducir azúcares refinados', completada: false },
    ],
  },
  // ========== PACIENTE 2 ==========
  {
    id: '6',
    pacienteId: '2',
    tipo: 'gastrointestinal',
    porcentaje: 40,
    fecha: '2024-04-20',
    tareas: [
      { id: '1', descripcion: 'Eliminar alimentos irritantes', completada: false },
      { id: '2', descripcion: 'Glutamina en ayunas', completada: false },
      { id: '3', descripcion: 'Comer sin prisas', completada: false },
    ],
  },
  {
    id: '7',
    pacienteId: '2',
    tipo: 'datosCliniclos',
    porcentaje: 35,
    fecha: '2024-04-20',
    tareas: [
      { id: '1', descripcion: 'Reducir grasas saturadas', completada: false },
      { id: '2', descripcion: 'Omega 3 - 2g/día', completada: true },
      { id: '3', descripcion: 'Fibra soluble 25g/día', completada: false },
      { id: '4', descripcion: 'Ejercicio aeróbico 30 min/día', completada: false },
    ],
  },
  {
    id: '8',
    pacienteId: '2',
    tipo: 'rendimientoDeportivo',
    porcentaje: 25,
    fecha: '2024-04-20',
    tareas: [
      { id: '1', descripcion: 'Comenzar con caminatas 20 min', completada: false },
      { id: '2', descripcion: 'Hidratación pre-ejercicio', completada: false },
      { id: '3', descripcion: 'Proteína post-ejercicio', completada: false },
    ],
  },
  {
    id: '9',
    pacienteId: '2',
    tipo: 'biorritmo',
    porcentaje: 30,
    fecha: '2024-04-20',
    tareas: [
      { id: '1', descripcion: 'Horario regular de sueño', completada: false },
      { id: '2', descripcion: 'Melatonina 1mg si necesario', completada: false },
      { id: '3', descripcion: 'Reducir cafeína después de 14h', completada: false },
    ],
  },
];
